const rbacConfig = {
  entities: {
    invoice: {
      create: ['owner', 'manager', 'accountant'],
      read: ['owner', 'manager', 'accountant'],
      update: ['owner', 'manager', 'accountant'],
      delete: ['owner'],
      list: ['owner', 'manager', 'accountant'],
      listAll: ['owner', 'manager', 'accountant'],
      search: ['owner', 'manager', 'accountant'],
      filter: ['owner', 'manager', 'accountant'],
      summary: ['owner', 'manager', 'accountant'],
      mail: ['owner', 'manager', 'accountant'],
      approveUpdate: ['owner', 'manager'],
      rejectUpdate: ['owner', 'manager'],
    },
    quote: {
      create: ['owner', 'manager', 'accountant'],
      read: ['owner', 'manager', 'accountant'],
      update: ['owner', 'manager', 'accountant'],
      delete: ['owner'],
      list: ['owner', 'manager', 'accountant'],
      listAll: ['owner', 'manager', 'accountant'],
      search: ['owner', 'manager', 'accountant'],
      filter: ['owner', 'manager', 'accountant'],
      summary: ['owner', 'manager', 'accountant'],
      mail: ['owner', 'manager', 'accountant'],
      convert: ['owner', 'manager'],
    },
    payment: {
      create: ['owner', 'manager', 'accountant'],
      read: ['owner', 'manager', 'accountant'],
      update: ['owner'],
      delete: ['owner'],
      list: ['owner', 'manager', 'accountant'],
      listAll: ['owner', 'manager', 'accountant'],
      search: ['owner', 'manager', 'accountant'],
      filter: ['owner', 'manager', 'accountant'],
      summary: ['owner', 'manager', 'accountant'],
      mail: ['owner', 'manager', 'accountant'],
      approveUpdate: ['owner', 'manager'],
      rejectUpdate: ['owner', 'manager'],
    },
    client: {
      create: ['owner', 'manager'],
      read: ['owner', 'manager', 'accountant'],
      update: ['owner', 'manager'],
      delete: ['owner'],
      list: ['owner', 'manager', 'accountant'],
      listAll: ['owner', 'manager', 'accountant'],
      search: ['owner', 'manager', 'accountant'],
      filter: ['owner', 'manager', 'accountant'],
      summary: ['owner', 'manager', 'accountant'],
      report: ['owner', 'manager', 'accountant'],
    },
    booking: {
      create: ['owner', 'manager'],
      read: ['owner', 'manager', 'accountant'],
      update: ['owner', 'manager'],
      delete: ['owner'],
      list: ['owner', 'manager', 'accountant'],
      listAll: ['owner', 'manager', 'accountant'],
      search: ['owner', 'manager', 'accountant'],
      filter: ['owner', 'manager', 'accountant'],
      summary: ['owner', 'manager', 'accountant'],
      receipt: ['owner', 'manager', 'accountant'],
    },
    expense: {
      create: ['owner', 'manager', 'accountant'],
      read: ['owner', 'manager', 'accountant'],
      update: ['owner', 'manager', 'accountant'],
      delete: ['owner'],
      list: ['owner', 'manager', 'accountant'],
      listAll: ['owner', 'manager', 'accountant'],
      search: ['owner', 'manager', 'accountant'],
      filter: ['owner', 'manager', 'accountant'],
      summary: ['owner', 'manager', 'accountant'],
    },
    pettycashtransaction: {
      create: ['owner', 'manager', 'accountant'],
      read: ['owner', 'manager', 'accountant'],
      update: ['owner', 'manager', 'accountant'],
      delete: ['owner'],
      list: ['owner', 'manager', 'accountant'],
      listAll: ['owner', 'manager', 'accountant'],
      search: ['owner', 'manager', 'accountant'],
      filter: ['owner', 'manager', 'accountant'],
      summary: ['owner', 'manager', 'accountant'],
      report: ['owner', 'manager', 'accountant'],
    },
    // Construction/Site logs (engineers have full read/write, accountants have read)
    villa: {
      create: ['owner', 'manager'],
      read: ['owner', 'manager', 'engineer', 'accountant'],
      update: ['owner', 'manager'],
      delete: ['owner'],
      list: ['owner', 'manager', 'engineer', 'accountant'],
      listAll: ['owner', 'manager', 'engineer', 'accountant'],
      search: ['owner', 'manager', 'engineer', 'accountant'],
      filter: ['owner', 'manager', 'engineer', 'accountant'],
      summary: ['owner', 'manager', 'engineer', 'accountant'],
      downloadVillaReport: ['owner', 'manager', 'engineer', 'accountant'],
    },
    material: {
      create: ['owner', 'manager', 'engineer'],
      read: ['owner', 'manager', 'engineer', 'accountant'],
      update: ['owner', 'manager', 'engineer'],
      delete: ['owner'],
      list: ['owner', 'manager', 'engineer', 'accountant'],
      listAll: ['owner', 'manager', 'engineer', 'accountant'],
      search: ['owner', 'manager', 'engineer', 'accountant'],
      filter: ['owner', 'manager', 'engineer', 'accountant'],
      summary: ['owner', 'manager', 'engineer', 'accountant'],
      adjustStock: ['owner', 'manager', 'engineer'],
      history: ['owner', 'manager', 'engineer', 'accountant'],
      recentTransactions: ['owner', 'manager', 'engineer', 'accountant'],
      downloadReport: ['owner', 'manager', 'engineer', 'accountant'],
    },
    inventorytransaction: {
      create: ['owner', 'manager', 'engineer'],
      read: ['owner', 'manager', 'engineer', 'accountant'],
      update: ['owner', 'manager', 'engineer'],
      delete: ['owner'],
      list: ['owner', 'manager', 'engineer', 'accountant'],
      listAll: ['owner', 'manager', 'engineer', 'accountant'],
      search: ['owner', 'manager', 'engineer', 'accountant'],
      filter: ['owner', 'manager', 'engineer', 'accountant'],
      summary: ['owner', 'manager', 'engineer', 'accountant'],
    },
    goodsreceipt: {
      create: ['owner', 'manager', 'engineer'],
      read: ['owner', 'manager', 'engineer', 'accountant'],
      update: ['owner', 'manager', 'engineer'],
      delete: ['owner'],
      list: ['owner', 'manager', 'engineer', 'accountant'],
      listAll: ['owner', 'manager', 'engineer', 'accountant'],
      search: ['owner', 'manager', 'engineer', 'accountant'],
      filter: ['owner', 'manager', 'engineer', 'accountant'],
      summary: ['owner', 'manager', 'engineer', 'accountant'],
    },
    project: {
      create: ['owner', 'manager'],
      read: ['owner', 'manager', 'engineer', 'accountant'],
      update: ['owner', 'manager'],
      delete: ['owner'],
      list: ['owner', 'manager', 'engineer', 'accountant'],
      listAll: ['owner', 'manager', 'engineer', 'accountant'],
      search: ['owner', 'manager', 'engineer', 'accountant'],
      filter: ['owner', 'manager', 'engineer', 'accountant'],
      summary: ['owner', 'manager', 'engineer', 'accountant'],
    },
    labour: {
      create: ['owner', 'manager', 'engineer'],
      read: ['owner', 'manager', 'engineer', 'accountant'],
      update: ['owner', 'manager', 'engineer'],
      delete: ['owner'],
      list: ['owner', 'manager', 'engineer', 'accountant'],
      listAll: ['owner', 'manager', 'engineer', 'accountant'],
      search: ['owner', 'manager', 'engineer', 'accountant'],
      filter: ['owner', 'manager', 'engineer', 'accountant'],
      summary: ['owner', 'manager', 'engineer', 'accountant'],
    },
    attendance: {
      create: ['owner', 'manager', 'engineer'],
      read: ['owner', 'manager', 'engineer', 'accountant'],
      update: ['owner', 'manager', 'engineer'],
      delete: ['owner'],
      list: ['owner', 'manager', 'engineer', 'accountant'],
      listAll: ['owner', 'manager', 'engineer', 'accountant'],
      search: ['owner', 'manager', 'engineer', 'accountant'],
      filter: ['owner', 'manager', 'engineer', 'accountant'],
      summary: ['owner', 'manager', 'engineer', 'accountant'],
    },
    supplier: {
      create: ['owner', 'manager'],
      read: ['owner', 'manager', 'accountant', 'engineer'],
      update: ['owner', 'manager'],
      delete: ['owner'],
      list: ['owner', 'manager', 'accountant', 'engineer'],
      listAll: ['owner', 'manager', 'accountant', 'engineer'],
      search: ['owner', 'manager', 'accountant', 'engineer'],
      filter: ['owner', 'manager', 'accountant', 'engineer'],
      summary: ['owner', 'manager', 'accountant', 'engineer'],
    },
    auditlog: {
      read: ['owner', 'manager'],
      list: ['owner', 'manager'],
      listAll: ['owner', 'manager'],
      search: ['owner', 'manager'],
      filter: ['owner', 'manager'],
      summary: ['owner', 'manager'],
    },
  }
};

module.exports = rbacConfig;
